version: "3"
interval: 500ms
tasks:
  default:
    cmds:
      - task: env-reload
  env-reload:
    cmds:
      - direnv reload
      - nix-direnv-reload
    aliases:
      - env
  git-gud:
    cmds:
      - git add --all
    silent: true
  run:
    cmds:
      - task: build-glsl
      - task: git-gud
      - nix run . --show-trace
    aliases:
      - test
  debug:
    deps:
      - build-debug
    cmds:
      - gdb debug/main --tui
    aliases:
      - d
  debug-dap:
    cmds:
      - gdb debug/main -i dap
  build-glsl:
    sources:
      - ./src/main/**.glsl
    cmds:
      - for: sources
        cmd: |
          sokol-shdc -i {{.ITEM}} \
          -o {{replace ".glsl" ".odin" .ITEM}} \
          -l "$(nix eval --raw ".#odinConfig.${system}.extraEnvVars.SLANG")" \
          -f "sokol_odin"
    method: none
  build:
    cmds:
      - task: build-glsl
      - task: git-gud
      - nix build . --show-trace
    aliases:
      - b
  build-test:
    deps:
      - mkdir-test
    cmds:
      - task: build-glsl
      - task: git-gud
      - eval cmd="$(nix eval ".#odinConfig.${system}.cli.test.cmd")" && eval "$cmd"
    env:
      src: ./src/main/
  mkdir-test:
    cmds:
      - rm -r test || true
      - mkdir test
    internal: true
  mkdir-debug:
    cmds:
      - rm -r debug || true
      - mkdir debug
    internal: true
  build-debug:
    deps:
      - mkdir-debug
    cmds:
      - task: build-glsl
      - task: git-gud
      - eval cmd="$(nix eval ".#odinConfig.${system}.cli.debug.cmd")" && eval "$cmd"
    aliases:
      - bd
    env:
      src: ./src/main/
  watch:
    watch: true
    sources:
      - "src/main/**/*.odin"
    cmds:
      - task: test
  watch-run:
    sources:
      - "src/main/**/*.odin"
    cmds:
      - task: run
