version: "3"
interval: 500ms
tasks:
  default:
    cmds:
      - task: env-reload
  env-reload:
    cmds:
      - direnv reload
      - nix-direnv-reload
    aliases:
      - env
  check-device:
    cmds:
      - sudo dfu-util -l
