version: "3"
interval: 500ms
tasks:
  default:
    cmds:
      - task: env-reload
  env-reload:
    cmds:
      - direnv reload
      - nix-direnv-reload
    aliases:
      - env
  build:
    cmds:
      - nickel eval ./src/main.ncl
    aliases:
      - test
