version: "3"
interval: 500ms
tasks:
  default:
    cmds:
      - task: env-reload
  env-reload:
    cmds:
      - direnv reload
      - nix-direnv-reload
    aliases:
      - env
  run:
    cmds:
      - go run
    method: none
    #  debug:
    #    deps:
    #      - build-debug
    #    cmds:
    #      - gdb debug/main --tui
    #    aliases:
    #      - d
    #    method: none
    #  debug-dap:
    #    cmds:
    #      - gdb debug/main -i dap
    #    method: none
  build:
    sources:
      - "*.go"
    cmds:
      - nix build
    aliases:
      - b
    generates:
      - result/
  build-test:
    cmds:
      - go test
    aliases:
      - test
    method: none
    #  mkdir-debug:
    #    precondition: "[ ! -e debug ]"
    #    sources:
    #      - "debug/"
    #    cmds:
    #      - mkdir debug
    #    internal: true
    #  build-debug:
    #    deps:
    #      - mkdir-debug
    #    sources:
    #      - "src/**/*.odin"
    #    cmds:
    #      - odin build src/main -out:debug/main -o:none -debug
    #    aliases:
    #      - bd
    #    generates:
    #      - debug/main
  watch:
    watch: true
    sources:
      - "*.go"
    cmds:
      - task: test
  watch-run:
    watch: true
    sources:
      - "*.go"
    cmds:
      - task: run
